name: AEOS DEBUG

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HARD DEBUG
        run: |
          echo "=== WHO AM I ==="
          pwd

          echo "=== ROOT ==="
          ls -la

          echo "=== FIND LOCKFILE ANYWHERE ==="
          find . -name "package-lock.json"

          echo "=== NODE VERSION ==="
          node -v

          echo "=== NPM VERSION ==="
          npm -v
